name: deploy-iac
run-name: "${{ github.event_name }} - ${{ github.run_id }} - by @${{ github.actor }}"
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: install azure-cli 2.72.0
        run: |
          sudo apt-get remove -y azure-cli
          pip install azure-cli==2.72.0

      - name: az login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          scope: "resourcegroup"
          deploymentName: "${{ github.workflow }}-${{ github.run_id }}"
          template: ./iac/main.bicep
          parameters: ""
          failOnStdErr: false
